SITE = "prodigy"
ROOM = "cmcm"
BOARD_ID = "mb-001"

DEBUG_REPL = True
DEBUG_BUFFER_SIZE = 50

# Raspberry Pi Pico-class boards expose USB VBUS sense on GPIO24.
# If USB is connected and AUTO_RUN_WITH_USB_CONNECTED is False, boot.py leaves
# the firmware stopped at the REPL for development and recovery.
USB_VBUS_DETECT_PIN = 24
AUTO_RUN_WITH_USB_CONNECTED = False

MQTT_HOST = "192.168.0.19"
MQTT_PORT = 1883
MQTT_USERNAME = None
MQTT_PASSWORD = None
MQTT_KEEPALIVE_SECONDS = 30
MQTT_ENABLED = True
MQTT_QOS = 1

TOPIC_ROOT = "morseflow/{}/{}/{}".format(SITE, ROOM, BOARD_ID)

NETWORK_DHCP = True

# Used only when NETWORK_DHCP is False.
STATIC_IP = "192.168.10.51"
STATIC_SUBNET = "255.255.255.0"
STATIC_GATEWAY = "192.168.10.1"
STATIC_DNS = "192.168.10.1"

RECONNECT_INTERVAL_MS = 5000
STATUS_INTERVAL_MS = 30000
APP_LOOP_ERROR_BACKOFF_MS = 1000
NETWORK_WAIT_LOG_INTERVAL_MS = 5000

PROP_5V_ENABLED_AT_BOOT = False
RELAY_ENABLED_AT_BOOT = False
PORT_SIGNALS_HIGH_AT_BOOT = False
